#!/bin/python

#function ctrl_c() {
#        echo "**You pressed Ctrl+C...Exiting"
#	exit 0;
#}

import os 

print ("################################################")
print ("################################################")
print ("################################################")

print ("_    _                 _          _ _ _   ")
print ("| |  (_)_ _ _  ___ __  /_\ _  _ __| (_) |_ ")
print ("| |__| |   \ || \ \ / / _ \ || / _  | |  _|")
print ("|____|_|_||_\_ _/_\_\/_/ \_\_ _\__ _|_|\__|") 
print ("###############################################")
print ("Welcome to security audit of your linux machine:")
print ("###############################################")
print ("Script will automatically gather the required info:")
print ("The checklist can help you in the process of hardening your system:")
print ("Note: it has been tested for Debian Linux Distro:")
os.system('sleep 3')
print ("###############################################")
print ("OK....$HOSTNAME..lets move on...wait for it to finish:")
os.system('sleep 3')
print ("Script Starts ;)")
os.system('START=$(date +%s)')
print  (" Linux Kernel Information")
os.system('uname -a')
print ("###############################################")
print  (" Current User and ID information")
os.system('whoami')
os.system('id')
print ("###############################################")
print ("Linux Distribution Information")
os.system('lsb_release -a')
print ("###############################################")
print  ("List Current Logged In Users")
os.system('w')
print ("###############################################")
print ("HOSTNAME uptime Information")
os.system('uptime')
print ("###############################################")
print  ("Running Services")
os.system('service --status-all |grep "+"')
print ("###############################################")
print  ("Active internet connections and open ports")
os.system('netstat -natp')
print ("###############################################")
print  ("Check Available Space")
os.system('df')
print ("###############################################")
print  ("Check Memory")
os.system('free -h')
print ("###############################################")
print  (" History (Commands)")
os.system('history')
print ("###############################################")
print ("Network Interfaces")
os.system('ifconfig -a')
print ("###############################################")
print  ("IPtable Information")
os.system('iptables -L -n -v')
print ("###############################################")
print ("\e[0;33m 13. Check Running Processes///// \e[0m")
os.system('ps -a')
print ("###############################################")
print ("Check SSH Configuration")
os.system('cat /etc/ssh/sshd_config')
print ("###############################################")
print ("List all packages installed")
os.system('apt-cache pkgnames')
print ("###############################################")
print ("Network Parameters")
os.system('cat /etc/sysctl.conf')
print ("###############################################")
print ("Password Policies")
os.system('cat /etc/pam.d/common-password')
print ("###############################################")
print (" Check your Source List file")
os.system('cat /etc/apt/sources.list')
print ("###############################################")
print  ("Check for broken dependencies")
os.system('apt-get check')
print ("###############################################")
print  ("MOTD banner message")
os.system('cat /etc/motd')
print ("###############################################")
print ("List user names")
os.system('cut -d: -f1 /etc/passwd')
print ("###############################################")
print ("Check for null passwords")
users="$(cut -d: -f 1 /etc/passwd)"
for x in users:
    os.system('passwd -S $x |grep "NP"')
print ("###############################################")
print ("IP routing table") 
os.system('route')
print ("###############################################")
os.system('END=$(date +%s)') 
os.system('DIFF=$(( $END - $START ))')
print ("Script completed in $DIFF seconds :")

print('END')
